#!/usr/bin/env python

import sys

from dumbo_cpe_gui.dumbo_cpe import Scoreboard
from rqt_gui.main import Main

plugin = 'dumbo_cpe_gui'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Scoreboard.add_arguments))

