#!/usr/bin/env python

import sys

from rqt_dumbo_cpe.dumbo_cpe import DumboContactPointEstimation
from rqt_gui.main import Main

plugin = 'rqt_dumbo_cpe'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=DumboContactPointEstimation.add_arguments))

